language: node_js
node_js: node
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: >-
      yNODi7LXVIIW9E3WXvApMayTJE7PLbzPwQfnLb01ncvee6rh9HFY1eyEPnbgs7R1E1vKT6LLDt+sa2th+aEHvUOOuRYU5pvXv0C88c4MupNMDO4/ybP6I00aJ3KAmb6NjOdK5M00XM1r/aSbVy9ZdSs82sTB0EFnihPMH3HzvOOUmT7EZJqxQvWTuG/rxCLlACqENELnVyMvxLZw71gFecfQ+Qm24t7YXksqYsLoXpOQeLRv6gc1RL+4ypEvHaNp30HBZ0bePbStHcFQbqerPj0N/zt+fx5Hxn7WqTt9QP+bF9bG7lL17VQKycEEZjJTvjN+7LOoevZ8P3GtEbVHrI2e10Rk2+D7h+CJbgnmUDqJSPB3Da44hPhGVKBeLIfgduZVu5FYNzb6eB9APt05rCDuB51Q5k6KR1oyx/0+hbxAp2NCCmse+qEHM9a/6N+nyxUOjqW+bazVNm6Eeo5QcSni0UFWJbrp5vXjeLMGGxl49ZVhaJAHlTRnrs9obast6NWglZDey2oj8JCLkjB3b6NlgznGMJIaaBXx0MJftJMEHznKgrXbRAW85zqI2/7vIeGOj3gTjq7YHimltTvFVFdds/xuzMY84e58CvkMT3JT+L6H6pNjD3f2j7igAKTHH2PwJz/0QihxE2fb/PqiRfLHg+p6wbhT5a+N1h3eFuQ=
  'on':
    tags: true
    repo: canjs/can-dom-mutate
dist: xenial
services:
  - xvfb
